# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
baseurl: '/LakeWaterLevelData'
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title : Bibliography
  url : /bibliography/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    output: true
    feature_text: |
      ## <span style ="color:white"> Welcome to my blog </span>
    feature_image: "https://raw.githubusercontent.com/olivia1117/LakeWaterLevelData/gh-pages/blog_title_image_cropped.jpg"
    



